# Generated by Django 5.1.6 on 2025-04-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('from_bank', models.BigIntegerField()),
                ('from_account', models.CharField(max_length=50)),
                ('to_bank', models.BigIntegerField()),
                ('to_account', models.CharField(max_length=50)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=20)),
                ('receiving_currency', models.CharField(max_length=50)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_currency', models.CharField(max_length=50)),
                ('payment_format', models.CharField(max_length=50)),
                ('is_laundering', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='fraud_detec_timesta_9edfd6_idx'), models.Index(fields=['from_bank'], name='fraud_detec_from_ba_e9aa89_idx'), models.Index(fields=['to_bank'], name='fraud_detec_to_bank_818179_idx'), models.Index(fields=['receiving_currency'], name='fraud_detec_receivi_577f37_idx'), models.Index(fields=['payment_currency'], name='fraud_detec_payment_dfd097_idx'), models.Index(fields=['payment_format'], name='fraud_detec_payment_ade8c6_idx'), models.Index(fields=['is_laundering'], name='fraud_detec_is_laun_d0b57b_idx'), models.Index(fields=['processed'], name='fraud_detec_process_3faa48_idx')],
            },
        ),
    ]
