# Generated by Django 5.1.6 on 2025-04-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_laundering',
            field=models.BooleanField(),
        ),
    ]
